# Generated by Django 5.1.6 on 2025-04-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateBiodata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('marital_status', models.CharField(max_length=50)),
                ('disability', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_time', models.TimeField(blank=True, null=True)),
                ('birth_place', models.CharField(max_length=255)),
                ('current_city_country', models.CharField(max_length=255)),
                ('visa_status', models.CharField(blank=True, max_length=255, null=True)),
                ('children', models.CharField(blank=True, max_length=255, null=True)),
                ('height', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.CharField(blank=True, max_length=50, null=True)),
                ('education', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('monthly_income', models.CharField(blank=True, max_length=100, null=True)),
                ('shani_mangal', models.CharField(blank=True, max_length=50, null=True)),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('eating_habits', models.CharField(blank=True, max_length=50, null=True)),
                ('alcoholic_drinks', models.BooleanField(default=False)),
                ('smoke', models.BooleanField(default=False)),
                ('other_habits', models.TextField(blank=True, null=True)),
                ('legal_police_case', models.BooleanField(default=False)),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('father_mobile', models.CharField(max_length=20)),
                ('mother_mobile', models.CharField(max_length=20)),
                ('parents_residence_city', models.CharField(max_length=255)),
                ('type_of_brahmin', models.CharField(blank=True, max_length=255, null=True)),
                ('gotra', models.CharField(blank=True, max_length=255, null=True)),
                ('kuldevi', models.CharField(blank=True, max_length=255, null=True)),
                ('siblings', models.CharField(blank=True, max_length=255, null=True)),
                ('partner_location', models.CharField(blank=True, max_length=255, null=True)),
                ('partner_age_bracket', models.CharField(blank=True, max_length=100, null=True)),
                ('partner_education', models.CharField(blank=True, max_length=255, null=True)),
                ('other_specific_choice', models.TextField(blank=True, null=True)),
                ('photograph', models.ImageField(upload_to='photographs/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
