# Generated by Django 5.1.6 on 2025-04-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatebiodata',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidatebiodata',
            name='whatsapp_number',
            field=models.CharField(default='0000000000', max_length=20),
            preserve_default=False,
        ),
    ]
