# Generated by Django 5.1.6 on 2025-05-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0002_candidatebiodata_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatebiodata',
            name='disability_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidatebiodata',
            name='visa_status_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidatebiodata',
            name='disability',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='candidatebiodata',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], default='Single', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidatebiodata',
            name='shani_mangal',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='candidatebiodata',
            name='visa_status',
            field=models.CharField(choices=[('No Status', 'No Status'), ('Have Status', 'Have Status')], default='No Status', max_length=20),
        ),
    ]
