# Generated by Django 5.1.6 on 2025-05-06 06:20

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0003_candidatebiodata_disability_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatebiodata',
            name='nadi',
            field=models.CharField(blank=True, choices=[('Aadhya', 'Aadhya'), ('Madhya', 'Madhya'), ('Antya', 'Antya'), ("I Don't Know", "I Don't Know"), ("We Don't Believe", "We Don't Believe")], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidatebiodata',
            name='disability',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes'), ('Minor Problem', 'Minor Problem')], default='No', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidatebiodata',
            name='marital_status',
            field=models.CharField(choices=[('Never Married (Unmarried)', 'Never Married (Unmarried)'), ('One-Time Gol-dhana, but then Got Cancel', 'One-Time Gol-dhana, but then Got Cancel'), ('One-Time Engagement, but, then Got Cancel', 'One-Time Engagement, but, then Got Cancel'), ('Divorce (No Child)', 'Divorce (No Child)'), ('Divorce (Having Child)', 'Divorce (Having Child)'), ('Widow (No Child)', 'Widow (No Child)'), ('Widow(Having Child)', 'Widow(Having Child)'), ('Divorce (Annuled)', 'Divorce (Annuled)'), ('Divorce In Process', 'Divorce In Process'), ('Seperated', 'Seperated')], default='Single', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidatebiodata',
            name='photograph',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='candidatebiodata',
            name='shani_mangal',
            field=models.CharField(blank=True, choices=[('Yes (Nirdosh)', 'Yes (Nirdosh)'), ('Yes (Normal)', 'Yes (Normal)'), ('No', 'No'), ("Don't Know", "Don't Know"), ("Don't Believe", "Don't Believe")], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidatebiodata',
            name='visa_status',
            field=models.CharField(choices=[('Indian Citizen', 'Indian Citizen'), ('NRI - Student Visa', 'NRI - Student Visa'), ('NRI - Work Permit', 'NRI - Work Permit'), ('NRI - PR', 'NRI - PR'), ('NRI - Green Card (USA)', 'NRI - Green Card (USA)'), ('NRI - Blue Card (EU)', 'NRI - Blue Card (EU)'), ('NRI - Citizenship', 'NRI - Citizenship'), ('NRI - Visitor Visa', 'NRI - Visitor Visa'), ('NRI - H1B Visa', 'NRI - H1B Visa')], default='Indian Citizen', max_length=30),
        ),
        migrations.AlterField(
            model_name='candidatebiodata',
            name='visa_status_details',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
