# Generated by Django 5.1.6 on 2025-05-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0004_candidatebiodata_nadi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatebiodata',
            name='marital_status',
            field=models.CharField(choices=[('Never Married', 'Never Married'), ('One Time Gol-Dhana But then Cancel', 'One Time Gol-Dhana But then Cancel'), ('One Time Engagement (Vivah) but afterwards cancel', 'One Time Engagement (Vivah) but afterwards cancel'), ('Divorce', 'Divorce'), ('Widow', 'Widow')], default='Never Married', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidatebiodata',
            name='nadi',
            field=models.CharField(blank=True, choices=[('Aadhya', 'Aadhya'), ('Madhya', 'Madhya'), ('Antya', 'Antya'), ('I Dont Know', 'I Dont Know'), ('We Dont Believe', 'We Dont Believe')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidatebiodata',
            name='shani_mangal',
            field=models.CharField(blank=True, choices=[('Yes ( Nirdosh )', 'Yes ( Nirdosh )'), ('Yes ( Normal)', 'Yes ( Normal)'), ('No', 'No'), ("Don't Know", "Don't Know"), ("Dont't Believe", "Dont't Believe")], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidatebiodata',
            name='visa_status',
            field=models.CharField(choices=[('Indian Citizen', 'Indian Citizen'), ('NRI - Student Visa', 'NRI - Student Visa'), ('NRI - Work Permit', 'NRI - Work Permit'), ('NRI - PR', 'NRI - PR'), ('NRI - Green Card (USA)', 'NRI - Green Card (USA)'), ('NRI - Blue Card (EU)', 'NRI - Blue Card (EU)'), ('NRI - Citizenship', 'NRI - Citizenship'), ('NRI - Visitor Visa', 'NRI - Visitor Visa'), ('NRI - H1B (USA)', 'NRI - H1B (USA)')], default='Indian Citizen', max_length=30),
        ),
    ]
