# Generated by Django 5.1.6 on 2025-05-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0005_alter_candidatebiodata_marital_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatebiodata',
            name='current_country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidatebiodata',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='candidatebiodata',
            name='registrant_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='candidatebiodata',
            name='registration_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidatebiodata',
            name='residence_area_category',
            field=models.CharField(blank=True, choices=[('Gujarat Region (North , Central , South)', 'Gujarat Region (North , Central , South)'), ('Saurshtra - Kachchh Region', 'Saurshtra - Kachchh Region'), ('Mumbai - Maharashtra - Rest of India Region', 'Mumbai - Maharashtra - Rest of India Region'), ('NRI (Non Residential Indian - Any Visa) Region (Out of India)', 'NRI (Non Residential Indian - Any Visa) Region (Out of India)')], max_length=100, null=True),
        ),
    ]
