# Generated by Django 5.1.6 on 2025-05-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0006_candidatebiodata_current_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatebiodata',
            name='candidate_current_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
