# Generated by Django 5.1.6 on 2025-05-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0007_candidatebiodata_candidate_current_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatebiodata',
            name='education',
            field=models.CharField(choices=[('Undergraduate', 'Undergraduate (10th 12th Pass / Fail , Diploma , ITI , Not Completed Graduation)'), ('Graduate', 'Graduate (BA , B.Com. , B.Sc. , BE , BTech, LLB , B. Arch., BBA , BCA etc)'), ('Masters', 'Masters (MA , MCom., MSc., ME , MTech, M.Arch , M.Phil, etc Masters Degree holders)'), ('CA_CS_ICWA_CPA_ACCA_CIMA', 'CA , CS , ICWA , CPA , ACCA , CIMA , etc'), ('Doctor', 'Doctor - Medical - Pharmacy - Dentist - Physiotherapist - Paramedical - Nursing'), ('PhD_UPSC_GPSC', 'PhD , UPSC , GPSC (IAS , IPS, etc) , Mayor , Civil Services etc'), ('Other', 'Any Other Education Category')], max_length=255),
        ),
    ]
