# Generated by Django 5.1.6 on 2025-05-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0008_alter_candidatebiodata_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatebiodata',
            name='occupation',
            field=models.CharField(choices=[('Government Job', 'Government Job'), ('Private MNC Job', 'Private MNC Job'), ('Private Company Job', 'Private Company Job'), ('Self Employed (Own Practice)', 'Self Employed (Own Practice)'), ('Own Business / Free Lancing', 'Own Business / Free Lancing'), ('Student (Studies Running)', 'Student (Studies Running)'), ('Searching Job', 'Searching Job'), ('Home Works (ghar-kaam)', 'Home Works (ghar-kaam)'), ('Job + Business', 'Job + Business')], max_length=255),
        ),
    ]
