# Generated by Django 5.1.6 on 2025-05-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0009_alter_candidatebiodata_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatebiodata',
            name='declaration',
            field=models.CharField(blank=True, choices=[('Agree', 'Agree (ઉપર મુજબ હું માનું છું અને તેમ કરીશ) - મારો બાયોડેટા બુકલેટ માં ચોક્કસ સમાવેશ કરશોજી'), ('Disagree', 'Disagree (ઉપર મુજબ હું નહિ માનું)  - મારો બાયોડેટા કેન્સલ કરી દેજો')], max_length=20, null=True),
        ),
    ]
