# Generated by Django 5.1.6 on 2025-05-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0010_candidatebiodata_declaration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatebiodata',
            name='candidate_current_city',
            field=models.CharField(default='Unknown City', max_length=255),
            preserve_default=False,
        ),
    ]
