# Generated by Django 5.1.6 on 2025-05-09 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0011_alter_candidatebiodata_candidate_current_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatebiodata',
            name='current_city_country',
        ),
        migrations.RemoveField(
            model_name='candidatebiodata',
            name='disability',
        ),
        migrations.RemoveField(
            model_name='candidatebiodata',
            name='disability_details',
        ),
        migrations.RemoveField(
            model_name='candidatebiodata',
            name='parents_residence_city',
        ),
    ]
