# Generated by Django 5.2.1 on 2025-05-10 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0013_remove_candidatebiodata_alcoholic_drinks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatebiodata',
            name='occupation_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
