# Generated by Django 5.2.1 on 2025-05-14 05:06

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0014_candidatebiodata_occupation_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='candidatebiodata',
            name='occupation',
            field=models.CharField(choices=[('Government Job', 'Government Job'), ('Private MNC Job', 'Private MNC Job'), ('Self Employed (Own Practice)', 'Self Employed (Own Practice)'), ('Own Business', 'Own Business'), ('Job + Business', 'Job + Business'), ('Free Lancing', 'Free Lancing'), ('Student (Studies Running)', 'Student (Studies Running)'), ('Searching Job', 'Searching Job'), ('Home Works (ghar-kaam)', 'Home Works (ghar-kaam)')], max_length=255),
        ),
    ]
