# Generated by Django 5.2.1 on 2025-05-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0015_galleryimage_alter_candidatebiodata_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatebiodata',
            name='photograph',
            field=models.ImageField(upload_to='photographs/'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='gallery_images/'),
        ),
    ]
