# Generated by Django 5.2.1 on 2025-06-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0016_alter_candidatebiodata_photograph_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatebiodata',
            name='birth_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidatebiodata',
            name='dob',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidatebiodata',
            name='visa_status',
            field=models.CharField(choices=[('Indian Citizen', 'Indian Citizen'), ('NRI - Student Visa', 'NRI - Student Visa'), ('NRI - Work Permit', 'NRI - Work Permit'), ('NRI - PR', 'NRI - PR'), ('NRI - PR In Process', 'NRI - PR In Process'), ('NRI - Green Card (USA)', 'NRI - Green Card (USA)'), ('NRI - Blue Card (EU)', 'NRI - Blue Card (EU)'), ('NRI - Citizenship', 'NRI - Citizenship'), ('NRI - Visitor Visa', 'NRI - Visitor Visa'), ('NRI - H1B (USA)', 'NRI - H1B (USA)')], default='Indian Citizen', max_length=30),
        ),
    ]
