# Generated by Django 5.2.1 on 2025-06-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0017_alter_candidatebiodata_birth_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatebiodata',
            name='registrant_mobile',
            field=models.CharField(default=1234567890, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
