# Generated by Django 5.2.1 on 2025-06-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0018_alter_candidatebiodata_registrant_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancePassBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('pass_type', models.CharField(choices=[('silver', 'Silver Pass'), ('golden', 'Golden Pass')], max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('payment_screenshot', models.ImageField(upload_to='payment_screenshots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
