# Generated by Django 5.2.1 on 2025-06-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0019_advancepassbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancepassbooking',
            name='pass_type',
        ),
        migrations.RemoveField(
            model_name='advancepassbooking',
            name='quantity',
        ),
        migrations.AddField(
            model_name='advancepassbooking',
            name='entry_token_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advancepassbooking',
            name='tea_coffee_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advancepassbooking',
            name='unlimited_buffet_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
