# Generated by Django 5.2.1 on 2025-06-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0020_remove_advancepassbooking_pass_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceBookletBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('without_courier', models.BooleanField(default=False)),
                ('girls_booklet_without', models.BooleanField(default=False)),
                ('boys_booklet_without', models.BooleanField(default=False)),
                ('with_courier', models.BooleanField(default=False)),
                ('girls_booklet_with', models.BooleanField(default=False)),
                ('boys_booklet_with', models.BooleanField(default=False)),
                ('courier_address', models.TextField(blank=True, null=True)),
                ('payment_screenshot', models.ImageField(upload_to='payment_screenshots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
