# Generated by Django 5.2.1 on 2025-07-01 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0021_advancebookletbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancebookletbooking',
            name='boys_booklet_without',
        ),
        migrations.RemoveField(
            model_name='advancebookletbooking',
            name='girls_booklet_without',
        ),
        migrations.RemoveField(
            model_name='advancebookletbooking',
            name='without_courier',
        ),
    ]
