# Generated by Django 5.2.1 on 2025-07-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0022_remove_advancebookletbooking_boys_booklet_without_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancebookletbooking',
            name='with_courier',
            field=models.BooleanField(default=True),
        ),
    ]
