# Generated by Django 5.2.1 on 2025-07-02 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0023_alter_advancebookletbooking_with_courier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancebookletbooking',
            name='with_courier',
        ),
    ]
