# Generated by Django 5.2.1 on 2025-07-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0024_remove_advancebookletbooking_with_courier'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_candidate', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('current_city', models.CharField(max_length=100)),
                ('booklet_sr_no', models.CharField(max_length=100)),
                ('maritial_status', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=255)),
                ('job_business', models.CharField(max_length=255)),
                ('hobbies', models.CharField(max_length=255)),
                ('partner_choice', models.CharField(max_length=255)),
                ('photograph', models.ImageField(upload_to='photographs/')),
            ],
        ),
    ]
