# Generated by Django 5.2.1 on 2025-07-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0025_stageregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageregistration',
            name='dob',
            field=models.CharField(max_length=50),
        ),
    ]
