# Generated by Django 5.2.1 on 2025-07-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0026_alter_stageregistration_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageregistration',
            name='photograph',
            field=models.ImageField(upload_to='new_photographs/'),
        ),
    ]
