# Generated by Django 5.2.1 on 2025-07-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0028_spotadvancebookletbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stageregistration',
            name='booklet_sr_no',
        ),
        migrations.AlterField(
            model_name='stageregistration',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50),
        ),
    ]
