# Generated by Django 5.2.1 on 2025-07-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0029_remove_stageregistration_booklet_sr_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AstrologyFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('whatsapp', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('candidateName', models.CharField(max_length=100)),
                ('candidateDOB', models.CharField(max_length=100)),
                ('candidateBirthTime', models.CharField(max_length=100)),
                ('candidateBirthPlace', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
