# Generated by Django 5.2.1 on 2025-07-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0030_astrologyformsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('whatsapp', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('screenshot', models.ImageField(upload_to='screenshots/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
