# Generated by Django 5.1.6 on 2025-07-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0031_zoomregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='MegaBookletCorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('candidate_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('booklet_serial', models.CharField(max_length=100)),
                ('booklet_name', models.CharField(max_length=255)),
                ('correction_description', models.TextField()),
                ('submission_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
