# Generated by Django 5.1.6 on 2025-07-26 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0032_megabookletcorrectionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='megabookletcorrectionrequest',
            name='dob',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
