# Generated by Django 5.1.6 on 2025-07-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0033_megabookletcorrectionrequest_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='megabookletcorrectionrequest',
            name='photo_upload',
            field=models.ImageField(blank=True, null=True, upload_to='mega_correction_photos/'),
        ),
    ]
