# Generated by Django 5.2.1 on 2025-08-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0035_technicalsupportrequest_supportattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalsupportrequest',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
