# Generated by Django 5.2.1 on 2025-08-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0036_technicalsupportrequest_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalsupportrequest',
            name='category',
            field=models.CharField(choices=[('login_issue', 'Login Issue'), ('photo_update', 'Photo Update'), ('bio_data_posting', 'Bio Data Posting'), ('other', 'Other')], max_length=20),
        ),
    ]
