# Generated by Django 5.2.1 on 2025-08-14 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0037_alter_technicalsupportrequest_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicalsupportrequest',
            name='status',
        ),
    ]
