# Generated by Django 5.2.1 on 2025-08-14 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0038_create_business_directory_entry'),
        ('biodata', '0038_remove_technicalsupportrequest_status'),
    ]

    operations = [
    ]
