# Generated by Django 5.2.1 on 2025-08-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0039_merge_20250814_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdirectoryentry',
            name='business_type',
            field=models.CharField(choices=[('online', 'Online Business'), ('offline', 'Offline Business'), ('both', 'Online + Offline Business')], max_length=20),
        ),
        migrations.AlterField(
            model_name='businessdirectoryentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
