# Generated by Django 5.2.1 on 2025-08-14 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0040_alter_businessdirectoryentry_business_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessdirectoryentry',
            old_name='business_name',
            new_name='businessName',
        ),
        migrations.RenameField(
            model_name='businessdirectoryentry',
            old_name='business_type',
            new_name='businessType',
        ),
        migrations.RenameField(
            model_name='businessdirectoryentry',
            old_name='image',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='businessdirectoryentry',
            old_name='name',
            new_name='ownerName',
        ),
        migrations.RenameField(
            model_name='businessdirectoryentry',
            old_name='description',
            new_name='services',
        ),
    ]
