# Generated by Django 5.2.1 on 2025-08-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0041_rename_business_name_businessdirectoryentry_businessname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdirectoryentry',
            name='businessType',
            field=models.CharField(choices=[('Online Business', 'Online Business'), ('Offline Business', 'Offline Business'), ('Online + Offline Business', 'Online + Offline Business')], max_length=30),
        ),
        migrations.AlterField(
            model_name='businessdirectoryentry',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
