# Generated by Django 5.2.1 on 2025-08-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0042_alter_businessdirectoryentry_businesstype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdirectoryentry',
            name='website',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
