# Generated by Django 5.2.1 on 2025-08-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0043_alter_businessdirectoryentry_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdirectoryentry',
            name='ownerPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='business_directory/owner_photos/'),
        ),
    ]
