# Generated by Django 5.2.1 on 2025-08-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0044_businessdirectoryentry_ownerphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdirectoryentry',
            name='businessSegment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='businessdirectoryentry',
            name='cities',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='businessdirectoryentry',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
