# Generated by Django 5.2.1 on 2025-08-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0045_businessdirectoryentry_businesssegment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalKarmkandDirectoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('phone1', models.CharField(max_length=20)),
                ('phone2', models.CharField(blank=True, max_length=20, null=True)),
                ('brahman_activities', models.CharField(max_length=255)),
                ('experience_years', models.PositiveIntegerField()),
                ('other_skills', models.TextField(blank=True, null=True)),
                ('service_level', models.CharField(max_length=255)),
                ('employment_status', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='karmkand_photos/')),
                ('visiting_card', models.FileField(blank=True, null=True, upload_to='karmkand_visiting_cards/')),
                ('terms_agreed', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
