# Generated by Django 5.2.1 on 2025-08-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0046_globalkarmkanddirectoryentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicalsupportrequest',
            name='email',
        ),
        migrations.AddField(
            model_name='technicalsupportrequest',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
