# Generated by Django 5.2.1 on 2025-08-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0047_remove_technicalsupportrequest_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalkarmkanddirectoryentry',
            name='dob',
            field=models.CharField(max_length=50),
        ),
    ]
