# Generated by Django 5.2.1 on 2025-08-15 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0048_alter_globalkarmkanddirectoryentry_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalkarmkanddirectoryentry',
            old_name='brahman_activities',
            new_name='brahmanActivities',
        ),
        migrations.RenameField(
            model_name='globalkarmkanddirectoryentry',
            old_name='employment_status',
            new_name='employmentStatus',
        ),
        migrations.RenameField(
            model_name='globalkarmkanddirectoryentry',
            old_name='experience_years',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='globalkarmkanddirectoryentry',
            old_name='service_level',
            new_name='serviceLevel',
        ),
        migrations.RenameField(
            model_name='globalkarmkanddirectoryentry',
            old_name='other_skills',
            new_name='skills',
        ),
        migrations.RenameField(
            model_name='globalkarmkanddirectoryentry',
            old_name='terms_agreed',
            new_name='terms',
        ),
        migrations.RenameField(
            model_name='globalkarmkanddirectoryentry',
            old_name='visiting_card',
            new_name='visitingCard',
        ),
    ]
