# Generated by Django 5.2.1 on 2025-08-15 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0049_rename_brahman_activities_globalkarmkanddirectoryentry_brahmanactivities_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalkarmkanddirectoryentry',
            old_name='brahmanActivities',
            new_name='brahman_activities',
        ),
        migrations.RenameField(
            model_name='globalkarmkanddirectoryentry',
            old_name='employmentStatus',
            new_name='employment_status',
        ),
        migrations.RenameField(
            model_name='globalkarmkanddirectoryentry',
            old_name='experience',
            new_name='experience_years',
        ),
        migrations.RenameField(
            model_name='globalkarmkanddirectoryentry',
            old_name='skills',
            new_name='other_skills',
        ),
        migrations.RenameField(
            model_name='globalkarmkanddirectoryentry',
            old_name='serviceLevel',
            new_name='service_level',
        ),
        migrations.RenameField(
            model_name='globalkarmkanddirectoryentry',
            old_name='terms',
            new_name='terms_agreed',
        ),
        migrations.RenameField(
            model_name='globalkarmkanddirectoryentry',
            old_name='visitingCard',
            new_name='visiting_card',
        ),
    ]
