# Generated by Django 5.2.1 on 2025-08-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0050_rename_brahmanactivities_globalkarmkanddirectoryentry_brahman_activities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotadvancebookletbooking',
            name='booklet_camp_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='spotadvancebookletbooking',
            name='candidate_name_dob',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
