# Generated by Django 5.2.1 on 2025-08-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0051_spotadvancebookletbooking_booklet_camp_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotadvancebookletbooking',
            old_name='boys_booklet_with',
            new_name='divorce_widow_booklet',
        ),
        migrations.RenameField(
            model_name='spotadvancebookletbooking',
            old_name='girls_booklet_with',
            new_name='gujarat_boys_booklet',
        ),
        migrations.AddField(
            model_name='spotadvancebookletbooking',
            name='gujarat_girls_booklet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spotadvancebookletbooking',
            name='mumbai_booklet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spotadvancebookletbooking',
            name='nri_booklet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spotadvancebookletbooking',
            name='saurashtra_booklet',
            field=models.BooleanField(default=False),
        ),
    ]
