# Generated by Django 5.2.1 on 2025-08-21 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0052_rename_boys_booklet_with_spotadvancebookletbooking_divorce_widow_booklet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotadvancebookletbooking',
            name='courier_address',
        ),
    ]
