# Generated by Django 5.1.6 on 2025-09-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0053_remove_spotadvancebookletbooking_courier_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='BncBnfApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('date_of_birth', models.CharField(max_length=20)),
                ('marriage_status', models.CharField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried'), ('Divorce', 'Divorce'), ('Widow', 'Widow')], max_length=10)),
                ('whatsapp_number', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=15)),
                ('education', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('current_city', models.CharField(max_length=100)),
                ('home_address', models.TextField()),
            ],
        ),
    ]
