# Generated by Django 5.2.1 on 2025-09-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0055_garbapassregistration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garbapassregistration',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='garbapassregistration',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='garbapassregistration',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='garbapassregistration',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshots/'),
        ),
    ]
