# Generated by Django 5.2.1 on 2025-09-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0056_rename_full_name_garbapassregistration_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garbapassregistration',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='garbapassregistration',
            old_name='last_name',
            new_name='residence_city',
        ),
        migrations.RemoveField(
            model_name='garbapassregistration',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='garbapassregistration',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='garbapassregistration',
            name='marriage_status',
            field=models.CharField(blank=True, choices=[('Married', 'Married'), ('Unmarried', 'Unmarried'), ('Divorce', 'Divorce'), ('Widow', 'Widow')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='garbapassregistration',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
