# Generated by Django 5.2.1 on 2025-09-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0057_rename_first_name_garbapassregistration_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('expertise', models.CharField(max_length=255)),
                ('experience', models.PositiveIntegerField()),
                ('bio', models.TextField()),
                ('availability', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('terms', models.CharField(choices=[('yes', 'Yes, I Agree'), ('no', "No, I Don't Agree")], max_length=3)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='garbapassregistration',
            name='date_of_birth',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='garbapassregistration',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='garbapassregistration',
            name='marriage_status',
            field=models.CharField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried'), ('Divorce', 'Divorce'), ('Widow', 'Widow')], max_length=10),
        ),
        migrations.AlterField(
            model_name='garbapassregistration',
            name='residence_city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='garbapassregistration',
            name='whatsapp_number',
            field=models.CharField(max_length=15),
        ),
    ]
