# Generated by Django 5.2.1 on 2025-09-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0058_judge_alter_garbapassregistration_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garbapassregistration',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
