# Generated by Django 5.2.1 on 2025-09-20 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0060_participantregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garbapassregistration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='garbapassregistration',
            name='marriage_status',
        ),
    ]
