# Generated by Django 5.2.1 on 2025-09-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0061_remove_garbapassregistration_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudienceRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('ticket_quantity', models.PositiveIntegerField(default=1)),
                ('total_amount', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to='audience_payment_screenshots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
