# Generated by Django 5.2.1 on 2025-10-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0062_audienceregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivorceSammelanRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=200)),
                ('candidate_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('registrant_relation', models.CharField(max_length=100)),
                ('registrant_mobile', models.CharField(max_length=20)),
                ('candidate_current_city', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=30)),
                ('marital_status', models.CharField(choices=[('divorce_no_child', 'Divorce (No Child)'), ('divorce_child', 'Divorce (Having Child)'), ('widow_no_child', 'Widow (No Child)'), ('widow_child', 'Widow (Having Child)'), ('divorce_annulled', 'Divorce (Annuled)'), ('divorce_in_process', 'Divorce in Process'), ('separated', 'Separated')], max_length=30)),
                ('birth_time', models.CharField(blank=True, max_length=30)),
                ('birth_place', models.CharField(blank=True, max_length=100)),
                ('residence_area_category', models.CharField(choices=[('gujarat', 'Gujarat Region (North, Central, South)'), ('saurashtra', 'Saurshtra - Kachchh Region'), ('mumbai', 'Mumbai - Maharashtra - Rest of India Region'), ('nri', 'NRI (Non Residential Indian - Any Visa) Region (Out of India)')], max_length=50)),
                ('current_country', models.CharField(max_length=50)),
                ('visa_status', models.CharField(choices=[('indian', 'Indian Citizen'), ('nri_student', 'NRI - Student Visa'), ('nri_work', 'NRI - Work Permit'), ('nri_pr', 'NRI - PR'), ('nri_pr_process', 'NRI - PR In Process'), ('nri_green_card', 'NRI - Green Card (USA)'), ('nri_blue_card', 'NRI - Blue Card (EU)'), ('nri_citizenship', 'NRI - Citizenship'), ('nri_visitor', 'NRI - Visitor Visa'), ('nri_h1b', 'NRI - H1B (USA)')], max_length=30)),
                ('height', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('education_category', models.CharField(choices=[('undergraduate', 'Undergraduate'), ('graduate', 'Graduate'), ('masters', 'Masters'), ('ca_cs', 'CA, CS, ICWA, CPA, ACCA, CIMA, etc'), ('doctor_medical', 'Doctor - Medical - Pharmacy - Dentist - Physiotherapist - Paramedical - Nursing'), ('phd_civil', 'PhD, UPSC, GPSC, Mayor, Civil Services etc'), ('other', 'Any Other Education Category')], max_length=50)),
                ('occupation_category', models.CharField(choices=[('gov_job', 'Government Job'), ('private_job', 'Private MNC Job'), ('self_employed', 'Self Employed (Own Practice)'), ('own_business', 'Own Business'), ('job_business', 'Job + Business'), ('freelancing', 'Free Lancing'), ('student', 'Student (Studies Running)'), ('searching_job', 'Searching Job'), ('home_works', 'Home Works (ghar-kaam)')], max_length=30)),
                ('occupation_details', models.CharField(blank=True, max_length=200)),
                ('salary', models.CharField(blank=True, max_length=20)),
                ('shani_mangal', models.CharField(choices=[('yes_nirdosh', 'Yes (Nirdosh)'), ('yes_normal', 'Yes (Normal)'), ('no', 'No'), ('dont_know', "Don't Know"), ('dont_believe', "Don't Believe")], max_length=20)),
                ('nadi', models.CharField(choices=[('aadhya', 'Aadhya'), ('madhya', 'Madhya'), ('antya', 'Antya'), ('dont_know', 'I Dont Know'), ('dont_believe', 'We Dont Believe')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('father_mobile', models.CharField(max_length=20)),
                ('mother_mobile', models.CharField(max_length=20)),
                ('type_of_brahmin', models.CharField(max_length=100)),
                ('gotra', models.CharField(max_length=100)),
                ('kuldevi', models.CharField(blank=True, max_length=200)),
                ('siblings', models.CharField(blank=True, max_length=200)),
                ('partner_location', models.CharField(blank=True, max_length=100)),
                ('partner_age_bracket', models.CharField(blank=True, max_length=50)),
                ('partner_education', models.CharField(blank=True, max_length=100)),
                ('other_specific_choice', models.CharField(blank=True, max_length=200)),
                ('photograph', models.ImageField(upload_to='divorce_sammelan_photos/')),
                ('declaration', models.CharField(choices=[('agree', 'Agree (ઉપર મુજબ હું માનું છું)'), ('disagree', 'Disagree (ઉપર મુજબ હું નહિ માનું)')], max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
