# Generated by Django 5.2.1 on 2025-10-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0063_divorcesammelanregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divorcesammelanregistration',
            name='kuldevi',
        ),
        migrations.AddField(
            model_name='divorcesammelanregistration',
            name='disability',
            field=models.TextField(blank=True),
        ),
    ]
