# Generated by Django 5.2.1 on 2025-10-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0064_remove_divorcesammelanregistration_kuldevi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='divorcesammelanregistration',
            name='education_detail',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
