# Generated by Django 5.2.1 on 2025-10-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0065_divorcesammelanregistration_education_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('mobile_1', models.CharField(max_length=15)),
                ('mobile_2', models.CharField(blank=True, max_length=15, null=True)),
                ('mobile_3', models.CharField(blank=True, max_length=15, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('data_entry_person', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
