# Generated by Django 5.2.1 on 2025-10-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0066_birthdayformsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalkarmkanddirectoryentry',
            name='brahman_activities',
            field=models.CharField(max_length=255, verbose_name='કર્મકાંડ અને ક્રિયા-કર્મ'),
        ),
        migrations.AlterField(
            model_name='globalkarmkanddirectoryentry',
            name='dob',
            field=models.CharField(max_length=50, verbose_name='જન્મ-તારીખ'),
        ),
        migrations.AlterField(
            model_name='globalkarmkanddirectoryentry',
            name='employment_status',
            field=models.CharField(max_length=255, verbose_name='રોજગાર સ્થિતિ'),
        ),
        migrations.AlterField(
            model_name='globalkarmkanddirectoryentry',
            name='experience_years',
            field=models.PositiveIntegerField(verbose_name='અનુભવ વર્ષ'),
        ),
        migrations.AlterField(
            model_name='globalkarmkanddirectoryentry',
            name='location',
            field=models.CharField(max_length=255, verbose_name='હાલ નું રહેવાનું ગામ / શહેર નું નામ'),
        ),
        migrations.AlterField(
            model_name='globalkarmkanddirectoryentry',
            name='name',
            field=models.CharField(max_length=255, verbose_name='નામ (આપનું નામ)'),
        ),
        migrations.AlterField(
            model_name='globalkarmkanddirectoryentry',
            name='other_skills',
            field=models.TextField(blank=True, null=True, verbose_name='અન્ય કૌશલ્ય'),
        ),
        migrations.AlterField(
            model_name='globalkarmkanddirectoryentry',
            name='phone1',
            field=models.CharField(max_length=20, verbose_name='ફોન / WhatsApp નંબર 1'),
        ),
        migrations.AlterField(
            model_name='globalkarmkanddirectoryentry',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ફોન / WhatsApp નંબર 2'),
        ),
        migrations.AlterField(
            model_name='globalkarmkanddirectoryentry',
            name='photo',
            field=models.ImageField(upload_to='karmkand_photos/', verbose_name='ફોટો'),
        ),
        migrations.AlterField(
            model_name='globalkarmkanddirectoryentry',
            name='service_level',
            field=models.CharField(max_length=255, verbose_name='સેવા સ્તર'),
        ),
        migrations.AlterField(
            model_name='globalkarmkanddirectoryentry',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='સબમિટ થયેલ સમય'),
        ),
        migrations.AlterField(
            model_name='globalkarmkanddirectoryentry',
            name='terms_agreed',
            field=models.BooleanField(default=False, verbose_name='શરતો સ્વીકારેલ'),
        ),
        migrations.AlterField(
            model_name='globalkarmkanddirectoryentry',
            name='visiting_card',
            field=models.FileField(blank=True, null=True, upload_to='karmkand_visiting_cards/', verbose_name='વિઝિટિંગ કાર્ડ'),
        ),
    ]
