# Generated by Django 5.2.7 on 2025-10-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0067_alter_globalkarmkanddirectoryentry_brahman_activities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthdayformsubmission',
            name='data_entry_person',
        ),
        migrations.RemoveField(
            model_name='birthdayformsubmission',
            name='website',
        ),
        migrations.AlterField(
            model_name='globalkarmkanddirectoryentry',
            name='brahman_activities',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='globalkarmkanddirectoryentry',
            name='dob',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='globalkarmkanddirectoryentry',
            name='employment_status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='globalkarmkanddirectoryentry',
            name='experience_years',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='globalkarmkanddirectoryentry',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='globalkarmkanddirectoryentry',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='globalkarmkanddirectoryentry',
            name='other_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='globalkarmkanddirectoryentry',
            name='phone1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='globalkarmkanddirectoryentry',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='globalkarmkanddirectoryentry',
            name='photo',
            field=models.ImageField(upload_to='karmkand_photos/'),
        ),
        migrations.AlterField(
            model_name='globalkarmkanddirectoryentry',
            name='service_level',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='globalkarmkanddirectoryentry',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='globalkarmkanddirectoryentry',
            name='terms_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='globalkarmkanddirectoryentry',
            name='visiting_card',
            field=models.FileField(blank=True, null=True, upload_to='karmkand_visiting_cards/'),
        ),
    ]
