# Generated by Django 5.2.1 on 2025-10-31 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0069_storysubmission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storysubmission',
            options={'verbose_name': 'Share Your Wedding Story', 'verbose_name_plural': 'Share Your Wedding Stories'},
        ),
    ]
