# Generated by Django 5.2.1 on 2025-10-31 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0070_alter_storysubmission_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='storysubmission',
            name='boy_birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Boy Birth Date'),
        ),
        migrations.AddField(
            model_name='storysubmission',
            name='boy_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Boy City'),
        ),
        migrations.AddField(
            model_name='storysubmission',
            name='boy_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Boy Name'),
        ),
        migrations.AddField(
            model_name='storysubmission',
            name='function_date',
            field=models.DateField(blank=True, null=True, verbose_name='Function Date'),
        ),
        migrations.AddField(
            model_name='storysubmission',
            name='girl_birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Girl Birth Date'),
        ),
        migrations.AddField(
            model_name='storysubmission',
            name='girl_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Girl City'),
        ),
        migrations.AddField(
            model_name='storysubmission',
            name='girl_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Girl Name'),
        ),
        migrations.AddField(
            model_name='storysubmission',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Message (Optional)'),
        ),
        migrations.AddField(
            model_name='storysubmission',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Mobile Number'),
        ),
        migrations.AddField(
            model_name='storysubmission',
            name='relationship_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Candidate Relationship Status'),
        ),
        migrations.AddField(
            model_name='storysubmission',
            name='who_is_filling',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Who is Filling the Form'),
        ),
        migrations.AlterField(
            model_name='storysubmission',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Wedding Date'),
        ),
        migrations.AlterField(
            model_name='storysubmission',
            name='details',
            field=models.TextField(verbose_name='Share Your Wedding Story'),
        ),
        migrations.AlterField(
            model_name='storysubmission',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='story_images/', verbose_name='Photos'),
        ),
    ]
