# Generated by Django 5.2.7 on 2025-10-31 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0072_storyphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storysubmission',
            name='boy_birth_date',
        ),
        migrations.RemoveField(
            model_name='storysubmission',
            name='date',
        ),
        migrations.RemoveField(
            model_name='storysubmission',
            name='details',
        ),
        migrations.RemoveField(
            model_name='storysubmission',
            name='title',
        ),
        migrations.DeleteModel(
            name='StoryPhoto',
        ),
    ]
