# Generated by Django 5.2.1 on 2025-11-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0073_remove_storysubmission_boy_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storysubmission',
            name='boy_birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Boy Birth Date'),
        ),
    ]
