# Generated by Django 5.2.1 on 2025-11-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0074_storysubmission_boy_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='storysubmission',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='WhatsApp Number'),
        ),
    ]
