# Generated by Django 5.2.7 on 2025-11-27 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0075_storysubmission_whatsapp_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DivorceSammelanRegistration',
            new_name='BhudevSammelanRegistration',
        ),
    ]
