# Generated by Django 5.2.7 on 2025-11-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0076_rename_divorcesammelanregistration_bhudevsammelanregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bhudevsammelanregistration',
            name='id',
        ),
        migrations.AddField(
            model_name='bhudevsammelanregistration',
            name='sr_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bhudevsammelanregistration',
            name='marital_status',
            field=models.CharField(choices=[('never_married', 'Never Married'), ('gol_dhana_cancel', 'One Time Gol-Dhana But then Cancel'), ('engagement_cancel', 'One Time Engagement (Vivah) but afterwards cancel'), ('divorce', 'Divorce'), ('widow', 'Widow')], max_length=50),
        ),
    ]
