# Generated by Django 5.2.7 on 2025-12-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0077_remove_bhudevsammelanregistration_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatebiodata',
            name='marital_status',
            field=models.CharField(choices=[('never_married', 'Never Married (Unmarried)'), ('divorce_no_child', 'Divorce (No Child)'), ('divorce_having_child', 'Divorce (Having Child)'), ('widow_no_child', 'Widow (No Child)'), ('widow_having_child', 'Widow (Having Child)'), ('divorce_annulled', 'Divorce (Annulled)'), ('divorce_in_process', 'Divorce in Process'), ('separated', 'Separated'), ('gol_dhana_cancel', 'Gol-Dhana Done, but then Cancel'), ('engagement_cancel', 'Engagement Done, but then Cancel')], default='never_married', max_length=50),
        ),
    ]
