# Generated by Django 5.2.7 on 2025-12-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0078_alter_candidatebiodata_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatebiodata',
            name='residence_area_category',
            field=models.CharField(blank=True, choices=[('gujarat', 'Gujarat Region (North or Central or South)'), ('saurashtra', 'Saurashtra Region'), ('kachchh', 'Kachchh Region'), ('mumbai_maharashtra', 'Mumbai & Maharashtra Region'), ('rest_of_india', 'Root of Indian Region (except Gujarat & Maharashtra)'), ('nri', 'NRI (Any Visa)')], max_length=100, null=True),
        ),
    ]
