# Generated by Django 5.2.7 on 2025-12-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0079_alter_candidatebiodata_residence_area_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatebiodata',
            name='visa_status',
            field=models.CharField(choices=[('Indian Citizen', 'Indian Citizen'), ('NRI - Student Visa', 'NRI - Student Visa'), ('NRI - Work Permit', 'NRI - Work Permit'), ('NRI - PR', 'NRI - PR'), ('NRI - PR In Process', 'NRI - PR In Process'), ('NRI - Green Card (USA)', 'NRI - Green Card (USA)'), ('NRI - Blue Card (EU)', 'NRI - Blue Card (EU)'), ('NRI - Citizenship', 'NRI - Citizenship'), ('NRI - Visitor Visa', 'NRI - Visitor Visa'), ('NRI - H1B (USA)', 'NRI - H1B (USA)'), ('NRI - Business Visa', 'NRI - Business Visa'), ('NRI - OCI', 'NRI - OCI'), ('NRI - F1', 'NRI - F1')], default='Indian Citizen', max_length=30),
        ),
    ]
