# Generated by Django 5.2.7 on 2025-12-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0080_alter_candidatebiodata_visa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bhudevsammelanregistration',
            name='hobbies',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
