# Generated by Django 5.2.7 on 2025-12-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0081_bhudevsammelanregistration_hobbies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bhudevsammelanregistration',
            name='declaration',
        ),
        migrations.AlterField(
            model_name='bhudevsammelanregistration',
            name='education_category',
            field=models.CharField(choices=[('undergraduate', 'Undergraduate (10th 12th Pass / Fail , Diploma , ITI , Not Completed Graduation)'), ('graduate', 'Graduate (BA , B.Com. , B.Sc. , BE , BTech, LLB , B. Arch., BBA , BCA etc)'), ('masters', 'Masters (MA , MCom, MSc., ME , MTech, M.Arch , M.Phil, LLM, etc)'), ('ca_cs', 'CA , CS , ICWA, CPA, ACCA , CIMA , etc'), ('doctor_medical', 'Doctor - Medical - Pharmacy - Dentist - Physiotherapist - Paramedical - Nursing - Clinical Surgical - Specialists'), ('phd_civil', 'PhD , UPSC, GPSC (IAS , IPS, etc) , Mayor , Civil Services etc'), ('other', 'Any Other Education Category')], max_length=100),
        ),
        migrations.AlterField(
            model_name='bhudevsammelanregistration',
            name='marital_status',
            field=models.CharField(choices=[('never_married', 'Never Married (Unmarried)'), ('divorce_no_child', 'Divorce (No Child)'), ('divorce_having_child', 'Divorce (Having Child)'), ('widow_no_child', 'Widow (No Child)'), ('widow_having_child', 'Widow (Having Child)'), ('divorce_annulled', 'Divorce (Annulled)'), ('divorce_in_process', 'Divorce in Process'), ('separated', 'Separated'), ('gol_dhana_cancel', 'Gol-Dhana Done, but then Cancel'), ('engagement_cancel', 'Engagement Done, but then Cancel')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bhudevsammelanregistration',
            name='nadi',
            field=models.CharField(choices=[('aadhya', 'Aadhya Nadi'), ('madhya', 'Madhya Nadi'), ('antya', 'Antya Nadi'), ('dont_know', 'I Dont Know'), ('dont_believe', "We Don't Believe")], max_length=30),
        ),
        migrations.AlterField(
            model_name='bhudevsammelanregistration',
            name='occupation_category',
            field=models.CharField(choices=[('government_job', 'Government Job'), ('private_mnc_job', 'Private MNC Job'), ('self_employed', 'Self Employed (Own Practice)'), ('own_business', 'Own Business'), ('job_business', 'Job + Business'), ('free_lancing', 'Free Lancing'), ('student', 'Student (Studies Running)'), ('searching_job', 'Searching Job'), ('home_works', 'Home Works (ghar-kaam)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bhudevsammelanregistration',
            name='residence_area_category',
            field=models.CharField(choices=[('gujarat', 'Gujarat Region (North or Central or South)'), ('saurashtra', 'Saurashtra Region'), ('kachchh', 'Kachchh Region'), ('mumbai_maharashtra', 'Mumbai & Maharashtra Region'), ('rest_of_india', 'Root of Indian Region (except Gujarat & Maharashtra)'), ('nri', 'NRI (Any Visa)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bhudevsammelanregistration',
            name='shani_mangal',
            field=models.CharField(choices=[('yes_shani', 'Yes (Shani)'), ('yes_mangal', 'Yes (Mangal)'), ('no', 'No'), ('dont_know', "Don't Know"), ('dont_believe', "We Don't Believe")], max_length=30),
        ),
        migrations.AlterField(
            model_name='bhudevsammelanregistration',
            name='visa_status',
            field=models.CharField(choices=[('indian_citizen', 'Indian Citizen'), ('nri_student_visa', 'NRI - Student Visa'), ('nri_work_permit', 'NRI - Work Permit'), ('nri_pr', 'NRI - PR'), ('nri_pr_in_process', 'NRI - PR In Process'), ('nri_green_card_usa', 'NRI - Green Card (USA)'), ('nri_blue_card_eu', 'NRI - Blue Card (EU)'), ('nri_citizenship', 'NRI - Citizenship'), ('nri_visitor_visa', 'NRI - Visitor Visa'), ('nri_h1b_usa', 'NRI - H1B (USA)'), ('nri_business_visa', 'NRI - Business Visa'), ('nri_oci', 'NRI - OCI'), ('nri_f1', 'NRI - F1')], max_length=30),
        ),
    ]
