# Generated by Django 5.2.7 on 2025-12-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0082_remove_bhudevsammelanregistration_declaration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bhudevsammelanregistration',
            name='declaration',
            field=models.CharField(blank=True, choices=[('agree', 'Agree (ઉપર મુજબ હું માનું છું)'), ('disagree', 'Disagree (ઉપર મુજબ હું નહિ માનું)')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bhudevsammelanregistration',
            name='marital_status',
            field=models.CharField(choices=[('never_married', 'Never Married (Unmarried)'), ('divorce_no_child', 'Divorce (No Child)'), ('divorce_having_child', 'Divorce (Having Child)'), ('widow_no_child', 'Widow (No Child)'), ('widow_having_child', 'Widow (Having Child)'), ('divorce_annulled', 'Divorce (Annulled)'), ('divorce_in_process', 'Divorce in Process'), ('separated', 'Separated'), ('gol_dhana_cancel', '1 Time Gol-Dhana Done, but then Cancelled'), ('engagement_cancel', 'Engagement Done, but then Cancelled')], max_length=50),
        ),
    ]
