# Generated by Django 5.2.7 on 2025-12-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0083_bhudevsammelanregistration_declaration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bhudevsammelanregistration',
            name='alcohol',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True, verbose_name='Alcoholic Drinks?'),
        ),
        migrations.AddField(
            model_name='bhudevsammelanregistration',
            name='eating_habbits',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Eating Habits (Pure Veg?)'),
        ),
        migrations.AddField(
            model_name='bhudevsammelanregistration',
            name='kuldevi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bhudevsammelanregistration',
            name='legal_case',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Any Legal or Police Case?'),
        ),
        migrations.AddField(
            model_name='bhudevsammelanregistration',
            name='other_habbit',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Any Other Habit?'),
        ),
        migrations.AddField(
            model_name='bhudevsammelanregistration',
            name='smoke',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10, null=True, verbose_name='Smoke?'),
        ),
    ]
