# Generated by Django 5.2.7 on 2025-12-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0084_bhudevsammelanregistration_alcohol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bhudevsammelanregistration',
            name='hobbies',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Hobbies'),
        ),
        migrations.AlterField(
            model_name='bhudevsammelanregistration',
            name='nadi',
            field=models.CharField(blank=True, choices=[('aadhya', 'Aadhya'), ('madhya', 'Madhya'), ('antya', 'Antya'), ('dont_know', 'I Dont Know'), ('dont_believe', "We Don't Believe")], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bhudevsammelanregistration',
            name='residence_area_category',
            field=models.CharField(blank=True, choices=[('gujarat', 'Gujarat Region (North or Central or South)'), ('saurashtra', 'Saurashtra Region'), ('kachchh', 'Kachchh Region'), ('mumbai_maharashtra', 'Mumbai & Maharashtra Region'), ('rest_of_india', 'Rest of Indian Region (except Gujarat & Maharashtra)'), ('nri', 'NRI (Any Visa)')], max_length=50, null=True, verbose_name='Residence Area Category'),
        ),
    ]
