# Generated by Django 5.2.7 on 2025-12-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0085_alter_bhudevsammelanregistration_hobbies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bhudevsammelanregistration',
            name='education_category',
            field=models.CharField(choices=[('undergraduate', 'Undergraduate (10th 12th Pass / Fail , Diploma , ITI , Not Completed Graduation)'), ('graduate', 'Graduate (BA , B.Com. , B.Sc. , BE , BTech, LLB , B. Arch., BBA , BCA etc)'), ('masters', 'Masters (MA , MCom, MSc., ME , MTech, M.Arch , M.Phil, LLM, etc)'), ('ca_cs', 'CA , CS , ICWA, CPA, ACCA , CIMA , etc'), ('doctor_medical', 'Doctor - Medical - Pharmacy - Dentist - Physiotherapist - Paramedical - Nursing - Clinical Surgical - Specialists'), ('phd_civil', 'PhD , UPSC, GPSC (IAS , IPS, etc) , Mayor , Civil Services etc'), ('other', 'Any Other Education Category')], max_length=100, verbose_name='Education Category'),
        ),
        migrations.AlterField(
            model_name='bhudevsammelanregistration',
            name='shani_mangal',
            field=models.CharField(blank=True, choices=[('yes_shani', 'Yes (Shani)'), ('yes_mangal', 'Yes (Mangal)'), ('no', 'No'), ('dont_know', "Don't Know"), ('dont_believe', "We Don't Believe")], max_length=30, null=True, verbose_name='Shani / Mangal'),
        ),
    ]
