# Generated by Django 5.2.7 on 2025-12-17 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0086_alter_bhudevsammelanregistration_education_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Judge',
        ),
    ]
