# Generated by Django 5.2.7 on 2025-12-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0087_delete_judge'),
    ]

    operations = [
        migrations.CreateModel(
            name='SammelanPaymentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('date_of_birth', models.CharField(max_length=10, verbose_name='Date of Birth (DD-MM-YYYY)')),
                ('mobile_number', models.CharField(max_length=15, verbose_name='Mobile Number')),
                ('marital_status', models.CharField(choices=[('Never Married', 'Never Married'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=20, verbose_name='Marital Status')),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='payment_qr_codes/', verbose_name='QR Code')),
                ('payment_screenshot', models.ImageField(upload_to='payment_screenshots/', verbose_name='Payment Screenshot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
