# Generated by Django 5.2.7 on 2025-12-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0088_sammelanpaymentform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sammelanpaymentform',
            name='marital_status',
            field=models.CharField(max_length=100, verbose_name='Marital Status'),
        ),
    ]
