# Generated by Django 5.2.7 on 2025-12-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0089_alter_sammelanpaymentform_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sammelanpaymentform',
            name='candidate_email',
            field=models.EmailField(blank=True, default='', max_length=255, verbose_name='Candidate Email'),
        ),
    ]
