# Generated by Django 5.2.7 on 2025-12-30 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0090_sammelanpaymentform_candidate_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sammelanpaymentform',
            name='candidate_email',
        ),
    ]
