# Generated by Django 5.2.7 on 2026-01-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0091_remove_sammelanpaymentform_candidate_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='bhudevsammelanregistration',
            name='confirmation_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Confirmation Status (Admin)'),
        ),
        migrations.AddField(
            model_name='bhudevsammelanregistration',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('partial', 'Partial')], default='unpaid', max_length=20, verbose_name='Payment Status (Admin)'),
        ),
    ]
