# Generated by Django 5.2.7 on 2026-01-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0092_bhudevsammelanregistration_confirmation_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdirectoryentry',
            name='cities',
        ),
        migrations.AddField(
            model_name='businessdirectoryentry',
            name='service_locations',
            field=models.CharField(blank=True, max_length=200, verbose_name='Which City / State / Country You provide Your Business Services'),
        ),
    ]
