# Generated by Django 5.2.7 on 2026-01-05 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0093_remove_businessdirectoryentry_cities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancepassbooking',
            name='tea_coffee_quantity',
        ),
    ]
