# Generated by Django 5.2.7 on 2026-01-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0094_remove_advancepassbooking_tea_coffee_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stageregistration',
            name='education',
        ),
        migrations.RemoveField(
            model_name='stageregistration',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='stageregistration',
            name='job_business',
        ),
        migrations.RemoveField(
            model_name='stageregistration',
            name='maritial_status',
        ),
        migrations.RemoveField(
            model_name='stageregistration',
            name='partner_choice',
        ),
        migrations.RemoveField(
            model_name='stageregistration',
            name='photograph',
        ),
        migrations.AddField(
            model_name='stageregistration',
            name='whatsapp_number',
            field=models.CharField(default='NA', max_length=20),
        ),
    ]
