# Generated by Django 5.2.7 on 2026-02-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0096_divorcesammelanform'),
    ]

    operations = [
        migrations.CreateModel(
            name='PicnicRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filler_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('candidate_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('relation', models.CharField(choices=[('Self', 'Self'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Other', 'Other')], max_length=10)),
                ('dob', models.DateField()),
                ('persons', models.PositiveIntegerField()),
                ('is_coming', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='divorcesammelanform',
            options={'verbose_name': 'Divorce Sammelan Registration', 'verbose_name_plural': 'Divorce Sammelan Registrations'},
        ),
        migrations.AlterField(
            model_name='bhudevsammelanregistration',
            name='marital_status',
            field=models.CharField(choices=[('never_married', 'Never Married (Unmarried)'), ('divorce_no_child', 'Divorce (No Child)'), ('divorce_having_child', 'Divorce (Having Child)'), ('widow_no_child', 'Widow (No Child)'), ('widow_having_child', 'Widow (Having Child)'), ('divorce_annulled', 'Divorce (Annulled)'), ('divorce_in_process', 'Divorce in Process'), ('separated', 'Separated'), ('gol_dhana_cancel', '1 Time Gol-Dhana Done, but then Cancelled'), ('engagement_cancel', '1 Time Engagement Done, but then Cancelled')], max_length=50),
        ),
        migrations.AlterField(
            model_name='candidatebiodata',
            name='marital_status',
            field=models.CharField(choices=[('never_married', 'Never Married (Unmarried)'), ('divorce_no_child', 'Divorce (No Child)'), ('divorce_having_child', 'Divorce (Having Child)'), ('widow_no_child', 'Widow (No Child)'), ('widow_having_child', 'Widow (Having Child)'), ('divorce_annulled', 'Divorce (Annulled)'), ('divorce_in_process', 'Divorce in Process'), ('separated', 'Separated'), ('gol_dhana_cancel', '1 Time Gol-Dhana Done, but then Cancelled'), ('engagement_cancel', '1 Time Engagement Done, but then Cancelled')], default='never_married', max_length=50),
        ),
        migrations.AlterField(
            model_name='divorcesammelanform',
            name='marital',
            field=models.CharField(choices=[('never_married', 'Never Married (Unmarried)'), ('divorce_no_child', 'Divorce (No Child)'), ('divorce_having_child', 'Divorce (Having Child)'), ('widow_no_child', 'Widow (No Child)'), ('widow_having_child', 'Widow (Having Child)'), ('divorce_annulled', 'Divorce (Annulled)'), ('divorce_in_process', 'Divorce in Process'), ('separated', 'Separated'), ('gol_dhana_cancel', '1 Time Gol-Dhana Done, but then Cancelled'), ('engagement_cancel', '1 Time Engagement Done, but then Cancelled')], max_length=50),
        ),
    ]
