# Generated by Django 5.2.7 on 2026-02-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0097_picnicregistration_alter_divorcesammelanform_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='picnicregistration',
            name='email_address',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
