# Generated by Django 5.2.7 on 2026-02-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0098_picnicregistration_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='bncbnfapplication',
            name='area_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
