# Generated by Django 5.2.7 on 2026-02-21 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0100_courierbooklet35thbooking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courierbooklet35thbooking',
            options={'ordering': ['-created_at'], 'verbose_name': '35th Courier Booklet Booking', 'verbose_name_plural': '35th Courier Booklet Bookings'},
        ),
    ]
