# Generated by Django 5.2.7 on 2026-02-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0101_alter_courierbooklet35thbooking_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookletCampAdvBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('booking_date', models.DateField()),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
