# Generated by Django 5.2.7 on 2026-02-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0102_bookletcampadvbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookletcampadvbooking',
            name='additional_notes',
        ),
        migrations.RemoveField(
            model_name='bookletcampadvbooking',
            name='address',
        ),
        migrations.RemoveField(
            model_name='bookletcampadvbooking',
            name='email',
        ),
        migrations.AddField(
            model_name='bookletcampadvbooking',
            name='book',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookletcampadvbooking',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
