# Generated by Django 5.2.7 on 2026-02-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0104_bookletlibrarysubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='FortyPlusSammelan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.CharField(max_length=20)),
                ('marital', models.CharField(max_length=50)),
                ('disability', models.TextField(blank=True)),
                ('tob', models.CharField(blank=True, max_length=20)),
                ('birthPlace', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('height', models.CharField(blank=True, max_length=10)),
                ('weight', models.CharField(blank=True, max_length=10)),
                ('education', models.CharField(blank=True, max_length=100)),
                ('occupationCat', models.CharField(blank=True, max_length=100)),
                ('occupationDetails', models.TextField(blank=True)),
                ('salary', models.CharField(blank=True, max_length=20)),
                ('hobbies', models.CharField(blank=True, max_length=200)),
                ('father', models.CharField(blank=True, max_length=100)),
                ('mother', models.CharField(blank=True, max_length=100)),
                ('regMobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, upload_to='40plus_sammelan_photos/')),
                ('declaration', models.CharField(max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '40 Plus Sammelan Registration',
                'verbose_name_plural': '40 Plus Sammelan Registrations',
            },
        ),
    ]
