# Generated by Django 5.2.7 on 2026-02-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0105_fortyplussammelan'),
    ]

    operations = [
        migrations.AddField(
            model_name='fortyplussammelan',
            name='ageGap',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='fortyplussammelan',
            name='alcohol',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='fortyplussammelan',
            name='caste',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fortyplussammelan',
            name='eating_habbits',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fortyplussammelan',
            name='eduChoice',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fortyplussammelan',
            name='educationDetail',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fortyplussammelan',
            name='fatherWp',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='fortyplussammelan',
            name='gotra',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fortyplussammelan',
            name='kuldevi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fortyplussammelan',
            name='legal_case',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fortyplussammelan',
            name='locChoice',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fortyplussammelan',
            name='motherWp',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='fortyplussammelan',
            name='nadi',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fortyplussammelan',
            name='otherChoice',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fortyplussammelan',
            name='other_habbit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fortyplussammelan',
            name='resCat',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fortyplussammelan',
            name='shani',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='fortyplussammelan',
            name='siblings',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fortyplussammelan',
            name='smoke',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='fortyplussammelan',
            name='visa',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fortyplussammelan',
            name='who',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
