# Generated by Django 5.2.7 on 2026-03-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0108_bhudevkalakaar2026registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bhudevkalakaar2026registration',
            name='ageGroup',
            field=models.CharField(choices=[('10-20', '10 Yrs to 20 Yrs'), ('21-45', '21 Yrs to 45 Yrs')], max_length=20, verbose_name='Age Group'),
        ),
    ]
