# Generated by Django 5.2.7 on 2026-03-09 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0109_alter_bhudevkalakaar2026registration_agegroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bhudevkalakaar2026registration',
            name='event',
        ),
    ]
