# Generated by Django 5.2.7 on 2026-03-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0111_saurasthrakutchsammelan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sammelan37MumbaiMaharashtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.CharField(max_length=20)),
                ('marital', models.CharField(max_length=30)),
                ('disability', models.TextField()),
                ('tob', models.CharField(max_length=20)),
                ('birthPlace', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('visa', models.CharField(max_length=50)),
                ('height', models.CharField(max_length=20)),
                ('weight', models.CharField(max_length=20)),
                ('education', models.CharField(max_length=100)),
                ('educationDetail', models.CharField(max_length=100)),
                ('occupationCat', models.CharField(max_length=50)),
                ('occupationDetails', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=20)),
                ('shani', models.CharField(max_length=20)),
                ('hobbies', models.CharField(max_length=100)),
                ('father', models.CharField(max_length=100)),
                ('mother', models.CharField(max_length=100)),
                ('fatherWp', models.CharField(max_length=20)),
                ('motherWp', models.CharField(max_length=20)),
                ('caste', models.CharField(max_length=50)),
                ('gotra', models.CharField(max_length=50)),
                ('kuldevi', models.CharField(max_length=50)),
                ('siblings', models.TextField()),
                ('eating_habbits', models.CharField(max_length=50)),
                ('alcohol', models.CharField(max_length=10)),
                ('smoke', models.CharField(max_length=10)),
                ('other_habbit', models.CharField(max_length=50)),
                ('legal_case', models.CharField(max_length=100)),
                ('locChoice', models.CharField(max_length=100)),
                ('ageGap', models.CharField(max_length=50)),
                ('eduChoice', models.CharField(max_length=100)),
                ('otherChoice', models.TextField()),
                ('who', models.CharField(max_length=100)),
                ('regMobile', models.CharField(max_length=20)),
                ('resCat', models.CharField(max_length=50)),
                ('nadi', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='sammelan37_photos/')),
                ('declaration', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
