# Generated by Django 5.2.7 on 2026-03-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0114_flipbookaccessregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetTogetherRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=100, verbose_name='Candidate Name')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('parent', 'Parent')], max_length=20, verbose_name='Gender')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('city', models.CharField(max_length=100, verbose_name='Current City')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='WhatsApp No.')),
                ('members', models.CharField(choices=[('1', '1 Member'), ('2', '2 Members'), ('3', '3 Members'), ('4', '4 Members'), ('5+', '5+ Members')], max_length=10, verbose_name='Members Attending')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submission Date')),
            ],
            options={
                'verbose_name': 'Get-Together Registration',
                'verbose_name_plural': 'Get-Together Registrations',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
