# Generated by Django 5.2.7 on 2026-03-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0115_gettogetherregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='bncbnfapplication',
            name='dedication_time',
            field=models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Occasional', 'Occasional'), ('Very less time', 'Very less time')], default='', max_length=30),
        ),
    ]
