# Generated by Django 5.2.7 on 2026-04-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0116_bncbnfapplication_dedication_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBookResaleRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('standard', models.CharField(choices=[('Nursery', 'Nursery'), ('LKG', 'LKG'), ('UKG', 'UKG'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=10)),
                ('school', models.CharField(max_length=100)),
                ('board', models.CharField(choices=[('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('State Board', 'State Board'), ('IB', 'IB'), ('IGCSE', 'IGCSE'), ('Other', 'Other')], max_length=20)),
                ('mother_whatsapp', models.CharField(max_length=10)),
                ('father_whatsapp', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=100)),
                ('contact_details', models.TextField(blank=True)),
                ('participate', models.BooleanField(default=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.CharField(max_length=20)),
                ('marital', models.CharField(max_length=50)),
                ('disability', models.CharField(max_length=100)),
                ('tob', models.CharField(max_length=20)),
                ('birthPlace', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('visa', models.CharField(max_length=50)),
                ('height', models.CharField(max_length=20)),
                ('weight', models.CharField(max_length=20)),
                ('education', models.CharField(max_length=100)),
                ('educationDetail', models.CharField(max_length=200)),
                ('occupationCat', models.CharField(max_length=100)),
                ('occupationDetails', models.CharField(max_length=200)),
                ('salary', models.CharField(max_length=20)),
                ('shani', models.CharField(max_length=30)),
                ('hobbies', models.CharField(max_length=200)),
                ('father', models.CharField(max_length=100)),
                ('mother', models.CharField(max_length=100)),
                ('fatherWp', models.CharField(max_length=20)),
                ('motherWp', models.CharField(max_length=20)),
                ('caste', models.CharField(max_length=100)),
                ('gotra', models.CharField(max_length=100)),
                ('kuldevi', models.CharField(max_length=100)),
                ('siblings', models.TextField()),
                ('eating_habbits', models.CharField(max_length=100)),
                ('alcohol', models.CharField(max_length=10)),
                ('smoke', models.CharField(max_length=10)),
                ('other_habbit', models.CharField(max_length=100)),
                ('legal_case', models.CharField(max_length=100)),
                ('locChoice', models.CharField(max_length=100)),
                ('ageGap', models.CharField(max_length=20)),
                ('eduChoice', models.CharField(max_length=100)),
                ('otherChoice', models.TextField()),
                ('who', models.CharField(max_length=100)),
                ('regMobile', models.CharField(max_length=20)),
                ('resCat', models.CharField(max_length=50)),
                ('nadi', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='sammelan39_photos/')),
                ('declaration', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='sammelan39biodata',
            name='ageGap',
        ),
        migrations.RemoveField(
            model_name='sammelan39biodata',
            name='alcohol',
        ),
        migrations.RemoveField(
            model_name='sammelan39biodata',
            name='caste',
        ),
        migrations.RemoveField(
            model_name='sammelan39biodata',
            name='declaration',
        ),
        migrations.RemoveField(
            model_name='sammelan39biodata',
            name='eating_habbits',
        ),
        migrations.RemoveField(
            model_name='sammelan39biodata',
            name='eduChoice',
        ),
        migrations.RemoveField(
            model_name='sammelan39biodata',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sammelan39biodata',
            name='father',
        ),
        migrations.RemoveField(
            model_name='sammelan39biodata',
            name='fatherWp',
        ),
        migrations.RemoveField(
            model_name='sammelan39biodata',
            name='gotra',
        ),
        migrations.RemoveField(
            model_name='sammelan39biodata',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='sammelan39biodata',
            name='kuldevi',
        ),
        migrations.RemoveField(
            model_name='sammelan39biodata',
            name='legal_case',
        ),
        migrations.RemoveField(
            model_name='sammelan39biodata',
            name='locChoice',
        ),
        migrations.RemoveField(
            model_name='sammelan39biodata',
            name='mother',
        ),
        migrations.RemoveField(
            model_name='sammelan39biodata',
            name='motherWp',
        ),
        migrations.RemoveField(
            model_name='sammelan39biodata',
            name='nadi',
        ),
        migrations.RemoveField(
            model_name='sammelan39biodata',
            name='otherChoice',
        ),
        migrations.RemoveField(
            model_name='sammelan39biodata',
            name='other_habbit',
        ),
        migrations.RemoveField(
            model_name='sammelan39biodata',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='sammelan39biodata',
            name='regMobile',
        ),
        migrations.RemoveField(
            model_name='sammelan39biodata',
            name='resCat',
        ),
        migrations.RemoveField(
            model_name='sammelan39biodata',
            name='siblings',
        ),
        migrations.RemoveField(
            model_name='sammelan39biodata',
            name='smoke',
        ),
        migrations.RemoveField(
            model_name='sammelan39biodata',
            name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='sammelan39biodata',
            name='who',
        ),
    ]
