# Generated by Django 5.2.7 on 2026-04-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0117_studentbookresaleregistration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbookresaleregistration',
            name='father_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentbookresaleregistration',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
