# Generated by Django 5.2.7 on 2026-04-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0118_studentbookresaleregistration_father_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sammelan37mumbaimaharashtra',
            options={'verbose_name': '37th Sammelan - Mumbai & Maharashtra', 'verbose_name_plural': '37th Sammelan - Mumbai & Maharashtra'},
        ),
        migrations.AlterField(
            model_name='sammelan37mumbaimaharashtra',
            name='marital',
            field=models.CharField(choices=[('never_married', 'Never Married (Unmarried)'), ('divorce_no_child', 'Divorce (No Child)'), ('divorce_having_child', 'Divorce (Having Child)'), ('widow_no_child', 'Widow (No Child)'), ('widow_having_child', 'Widow (Having Child)'), ('divorce_annulled', 'Divorce (Annulled)'), ('divorce_in_process', 'Divorce in Process'), ('separated', 'Separated'), ('gol_dhana_cancel', '1 Time Gol-Dhana Done, but then Cancelled'), ('engagement_cancel', '1 Time Engagement Done, but then Cancelled')], default='never_married', max_length=30),
        ),
        migrations.AlterField(
            model_name='sammelan37mumbaimaharashtra',
            name='nadi',
            field=models.CharField(choices=[('aadhya_nadi', 'Aadhya Nadi'), ('madhya_nadi', 'Madhya Nadi'), ('antya_nadi', 'Antya Nadi'), ('dont_know', 'I Dont Know'), ('dont_believe', "We Don't Believe")], default='dont_know', max_length=20),
        ),
        migrations.AlterField(
            model_name='sammelan37mumbaimaharashtra',
            name='resCat',
            field=models.CharField(choices=[('gujarat_region', 'Gujarat Region (North or Central or South)'), ('saurashtra_region', 'Saurashtra Region'), ('kachchh_region', 'Kachchh Region'), ('mumbai_maharashtra', 'Mumbai & Maharashtra Region'), ('rest_of_india', 'Rest of Indian Region (except Gujarat & Maharashtra)'), ('nri', 'NRI (Any Visa)')], default='nri', max_length=50),
        ),
        migrations.AlterField(
            model_name='sammelan37mumbaimaharashtra',
            name='visa',
            field=models.CharField(choices=[('indian_citizen', 'Indian Citizen'), ('nri_student_visa', 'NRI - Student Visa'), ('nri_work_permit', 'NRI - Work Permit'), ('nri_pr', 'NRI - PR'), ('nri_pr_in_process', 'NRI - PR In Process'), ('nri_green_card_usa', 'NRI - Green Card (USA)'), ('nri_blue_card_eu', 'NRI - Blue Card (EU)'), ('nri_citizenship', 'NRI - Citizenship'), ('nri_visitor_visa', 'NRI - Visitor Visa'), ('nri_h1b_usa', 'NRI - H1B (USA)'), ('nri_business_visa', 'NRI - Business Visa'), ('nri_oci', 'NRI - OCI'), ('nri_f1', 'NRI - F1')], default='indian_citizen', max_length=50),
        ),
    ]
