# Generated by Django 5.2.7 on 2026-05-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0119_alter_sammelan37mumbaimaharashtra_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Your Name (Person filling this Form)')),
                ('city', models.CharField(max_length=100, verbose_name='Your City')),
                ('candidate_name', models.CharField(max_length=100, verbose_name='Your Candidate Name (Son/Daughter)')),
                ('candidate_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, verbose_name='Candidate Gender')),
                ('candidate_dob', models.DateField(verbose_name='Candidate Date of Birth')),
                ('mobile_no', models.CharField(max_length=15, verbose_name='Your Mobile No.')),
                ('whatsapp_no', models.CharField(max_length=15, verbose_name='Your WhatsApp No.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='sammelan37mumbaimaharashtra',
            options={'verbose_name': '37th Sammelan - UK & Europe', 'verbose_name_plural': '37th Sammelan - UK & Europe'},
        ),
    ]
