# Generated by Django 5.2.7 on 2026-07-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0123_sammelan38biodata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sammelan38biodata',
            name='education',
            field=models.CharField(choices=[('Doctor (Clinical - Surgical - Specialist)', 'Doctor (Clinical - Surgical - Specialist)'), ('Doctor (Physiotherapy)', 'Doctor (Physiotherapy)'), ('Doctor (Dental)', 'Doctor (Dental)'), ('Doctor (Pathology)', 'Doctor (Pathology)'), ('Doctor (Veterinary)', 'Doctor (Veterinary)'), ('Doctor (Ayurvedic)', 'Doctor (Ayurvedic)'), ('Doctor (Homeopathy)', 'Doctor (Homeopathy)'), ('Doctor (Naturopathy)', 'Doctor (Naturopathy)'), ('Pharmacy Education', 'Pharmacy Education'), ('Nurse - Midwifery', 'Nurse - Midwifery'), ('Paramedical Staff', 'Paramedical Staff'), ('Other Education Field', 'Other Education Field')], max_length=100),
        ),
    ]
