# Generated by Django 5.2.7 on 2026-07-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0124_alter_sammelan38biodata_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarriageDoneGiftSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filler_name', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('candidate_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('candidate_dob', models.DateField()),
                ('spouse_name', models.CharField(max_length=100)),
                ('spouse_dob', models.DateField()),
                ('wedding_photo', models.ImageField(upload_to='marriage_done_photos/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Marriage Done Gift Submission',
                'verbose_name_plural': 'Marriage Done Gift Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
