# Generated by Django 5.2.7 on 2026-08-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0127_samstagujaratregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='KarmkandiMaharajDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maharaj_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('laghurudra_experience', models.PositiveIntegerField()),
                ('residence_city', models.CharField(max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Karmkandi Maharaj Details',
                'verbose_name_plural': 'Karmkandi Maharaj Details',
            },
        ),
    ]
