# Generated by Django 5.2.7 on 2026-08-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0128_karmkandimaharajdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaghuRudraYajmanRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_by', models.CharField(max_length=255)),
                ('registered_mobile', models.CharField(max_length=15)),
                ('husband_name', models.CharField(max_length=255)),
                ('wife_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('full_address', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Laghu Rudra Yajman Registration',
                'verbose_name_plural': 'Laghu Rudra Yajman Registrations',
            },
        ),
    ]
