# Generated by Django 5.2.7 on 2026-08-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0129_laghurudrayajmanregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShivMandirShivalayInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temple_name', models.CharField(max_length=255)),
                ('priest_president_name', models.CharField(max_length=255)),
                ('priest_president_phone', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=255)),
                ('form_filled_by', models.CharField(max_length=255)),
                ('form_filler_phone', models.CharField(max_length=15)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Shiv Mandir / Shivalay Info',
                'verbose_name_plural': 'Shiv Mandir / Shivalay Info',
            },
        ),
    ]
