# Generated by Django 5.2.7 on 2026-08-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0130_shivmandirshivalayinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='samstagujaratregistration',
            options={'verbose_name': '39th Samasta Guj Sammelan Registration', 'verbose_name_plural': '39th Samasta Guj Sammelan Registrations'},
        ),
        migrations.AddField(
            model_name='laghurudrayajmanregistration',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('paid', 'Payment Success'), ('partial', 'Partial'), ('unpaid', 'Unpaid')], default='pending', max_length=20, verbose_name='Payment Status (Admin)'),
        ),
        migrations.AlterField(
            model_name='bhudevsammelanregistration',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('paid', 'Payment Success'), ('partial', 'Partial'), ('unpaid', 'Unpaid')], default='pending', max_length=20, verbose_name='Payment Status (Admin)'),
        ),
    ]
