# Generated by Django 5.2.7 on 2026-08-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0131_alter_samstagujaratregistration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='samstagujaratregistration',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('paid', 'Payment Success'), ('partial', 'Partial'), ('unpaid', 'Unpaid')], default='pending', max_length=20, verbose_name='Payment Status (Admin)'),
        ),
    ]
