# Generated by Django 5.2.7 on 2026-09-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0134_alter_samstagujaratregistration_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samstagujaratregistration',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Payment Success'), ('partial', 'Partial'), ('unpaid', 'Unpaid'), ('conf_pay_pending', 'Confirmation Done & Payment Pending'), ('paid_member', 'Paid Member'), ('cnr', 'CNR'), ('cancelled-form', 'Cancelled-Form')], default='pending', max_length=30, verbose_name='Payment Status (Admin)'),
        ),
    ]
