# Generated by Django 5.2.7 on 2026-09-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0135_alter_samstagujaratregistration_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancepassbooking',
            name='attend_city',
            field=models.CharField(choices=[('Vadodara', 'Vadodara (20-09-2026)'), ('Surat', 'Surat (27-09-2026)')], default='Vadodara', max_length=50, verbose_name='Which City Will You Attend?'),
        ),
    ]
