# Generated by Django 5.2.7 on 2026-09-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0136_advancepassbooking_attend_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancepassbooking',
            name='attend_city',
            field=models.CharField(choices=[('Vadodara', 'Vadodara (20-09-2026)'), ('Surat', 'Surat (27-09-2026)')], max_length=50, verbose_name='Which City Will You Attend?'),
        ),
    ]
