# Generated by Django 5.2.7 on 2026-09-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0138_mangalferasammelanbiodata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceBuffetLunchBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('attend_city', models.CharField(choices=[('Vadodara', 'Vadodara (20-09-2026)'), ('Surat', 'Surat (27-09-2026)')], max_length=50, verbose_name='Which City Will You Attend?')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Buffet Lunch Quantity')),
                ('payment_screenshot', models.ImageField(upload_to='payment_screenshots/buffet_lunch/')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Advance Unlimited Buffet Lunch Booking',
                'verbose_name_plural': 'Advance Unlimited Buffet Lunch Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvanceEntryPassBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('attend_city', models.CharField(choices=[('Vadodara', 'Vadodara (20-09-2026)'), ('Surat', 'Surat (27-09-2026)')], max_length=50, verbose_name='Which City Will You Attend?')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Pass Quantity')),
                ('payment_screenshot', models.ImageField(upload_to='payment_screenshots/entry_pass/')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Advance Entry + Tea Coffee Pass Booking',
                'verbose_name_plural': 'Advance Entry + Tea Coffee Pass Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='courierbooklet35thbooking',
            options={'ordering': ['-created_at'], 'verbose_name': '39th Courier Booklet Booking', 'verbose_name_plural': '39th Courier Booklet Bookings'},
        ),
        migrations.AlterField(
            model_name='courierbooklet35thbooking',
            name='courier_address',
            field=models.TextField(blank=True, null=True, verbose_name='Delivery Address (Phone number, area pincode)'),
        ),
    ]
