# Generated by Django 5.2.7 on 2026-09-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0139_advancebuffetlunchbooking_advanceentrypassbooking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sammelanpaymentform',
            name='area_pincode',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Area Pincode'),
        ),
        migrations.AddField(
            model_name='sammelanpaymentform',
            name='booklet_delivery_option',
            field=models.CharField(choices=[('courier', 'By Courier'), ('without_courier', 'Without Courier')], default='without_courier', max_length=20, verbose_name='Booklet Delivery Option'),
        ),
        migrations.AddField(
            model_name='sammelanpaymentform',
            name='delivery_address',
            field=models.TextField(blank=True, null=True, verbose_name='Delivery Address'),
        ),
    ]
