# Generated by Django 5.2.7 on 2026-09-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0140_sammelanpaymentform_area_pincode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageIntroduction39th',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('current_city', models.CharField(max_length=100)),
                ('event_city', models.CharField(max_length=255)),
                ('confirmation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
