# Generated by Django 5.2.7 on 2026-09-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0141_stageintroduction39th'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarsanStallBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=255, verbose_name='બહેનનું પૂરું નામ (Full Name)')),
                ('business_name', models.CharField(max_length=255, verbose_name='બિઝનેસ / સ્ટોલનું નામ (Business / Stall Name)')),
                ('business_type', models.CharField(choices=[('Farsan & Sweets', 'ફરસાણ અને મીઠાઈ (Farsan & Sweets)'), ('Food Stall & Snacks', 'ફૂડ સ્ટોલ / નાસ્તો (Food Stall & Snacks)'), ('Clothing & Dress Material', 'કપડાં / ડ્રેસ મટિરિયલ (Clothing & Dress)'), ('Jewellery & Imitation', 'જ્વેલરી / ઈમિટેશન (Jewellery)'), ('Handicraft & Home Decor', 'હેન્ડીક્રાફ્ટ / હોમ ડેકોર (Handicraft)'), ('Cosmetics & Beauty', 'કોસ્મેટિક્સ / બ્યૂટી (Cosmetics)'), ('Other Business / Service', 'અન્ય બિઝનેસ / સર્વિસ (Other Business)')], max_length=100, verbose_name='સ્ટોલનો પ્રકાર (Stall Type)')),
                ('city', models.CharField(max_length=100, verbose_name='હાલનું શહેર (Current City)')),
                ('whatsapp_number', models.CharField(max_length=20, verbose_name='વોટ્સએપ નંબર (WhatsApp No.)')),
                ('email', models.EmailField(max_length=254, verbose_name='ઈમેલ (Email ID)')),
                ('event_city', models.CharField(choices=[('Vadodara', 'Vadodara (20-09-2026)'), ('Surat', 'Surat (27-09-2026)'), ('Both', 'Both Vadodara & Surat')], max_length=50, verbose_name='ઇવેન્ટ સીટી (Event City)')),
                ('is_free_stall', models.BooleanField(default=False, verbose_name='100% Free Stall Quota')),
                ('stall_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stall Fee (₹)')),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to='payment_screenshots/farsan_stall/', verbose_name='Payment Screenshot')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='રજીસ્ટ્રેશન તારીખ')),
            ],
            options={
                'verbose_name': 'Business / Farsan Stall Registration',
                'verbose_name_plural': 'Business / Farsan Stall Registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
