# Generated by Django 5.2.7 on 2026-09-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0142_farsanstallbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancebuffetlunchbooking',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verified / Paid (Tick Mark)'),
        ),
        migrations.AddField(
            model_name='advanceentrypassbooking',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Verified / Paid (Tick Mark)'),
        ),
    ]
