# Generated by Django 5.2.7 on 2026-09-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0143_advancebuffetlunchbooking_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farsanstallbooking',
            name='is_free_stall',
        ),
        migrations.AlterField(
            model_name='farsanstallbooking',
            name='stall_fee',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10, verbose_name='Stall Fee (₹)'),
        ),
    ]
