# Generated by Django 5.2.7 on 2026-09-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0144_remove_farsanstallbooking_is_free_stall_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateGroupPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=255, verbose_name='Candidate Name')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('city', models.CharField(max_length=150, verbose_name='Current City')),
                ('education', models.CharField(max_length=255, verbose_name='Education')),
                ('photo', models.ImageField(upload_to='candidate_group_photos/', verbose_name='Candidate Photo')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
            ],
            options={
                'verbose_name': 'Candidate Group Posting',
                'verbose_name_plural': 'Candidate Group Postings',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
