# Generated by Django 5.2.7 on 2026-09-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0145_candidategroupposting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidategroupposting',
            name='dob',
            field=models.CharField(max_length=100, verbose_name='Date of Birth / Age'),
        ),
    ]
