# Generated by Django 5.2.7 on 2026-09-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0146_candidategroupposting_dob_char'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageintroduction39th',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stageintroduction39th',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='stage_intro_photos/'),
        ),
    ]
