# Generated by Django 5.2.7 on 2026-09-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0147_stageintro_edu_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farsanstallbooking',
            name='event_city',
            field=models.CharField(choices=[('Surat', 'Surat (27-09-2026)')], max_length=50, verbose_name='ઇવેન્ટ સીટી (Event City)'),
        ),
    ]
