# Generated by Django 5.2.7 on 2026-09-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0148_farsanstall_surat_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='samstagujaratregistration',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='samstagujaratregistration',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='samstagujaratregistration',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
