# Generated by Django 5.2.7 on 2026-09-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0149_samsta_gujarat_razorpay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangalferasammelanbiodata',
            name='caste',
            field=models.CharField(max_length=100, verbose_name='Type of Cast'),
        ),
        migrations.AlterField(
            model_name='mangalferasammelanbiodata',
            name='gotra',
            field=models.CharField(blank=True, max_length=100, verbose_name='Gotra (if applicable)'),
        ),
        migrations.AlterField(
            model_name='mangalferasammelanbiodata',
            name='kuldevi',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kuldevi (if applicable)'),
        ),
        migrations.AlterField(
            model_name='mangalferasammelanbiodata',
            name='nadi',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nadi (if applicable)'),
        ),
    ]
