# Generated by Django 6.1.1 on 2026-10-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0150_mangalfera_fields_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laghurudrayajmanregistration',
            options={'verbose_name': 'Navchandi Yajman Registration Form', 'verbose_name_plural': 'Navchandi Yajman Registration Form'},
        ),
        migrations.AlterField(
            model_name='mangalferasammelanbiodata',
            name='caste',
            field=models.CharField(max_length=100, verbose_name='Type of Caste'),
        ),
    ]
